### PR TITLE
Added My Selenium Test to Test the About button.

### PR DESCRIPTION
**Pull request by adrianhumphrey111**

### CODE REVIEW

**Comment by djp3** [comment]
So, adding a test that checks for a 404 error is missing the point.  You should be adding a test so that if a 404 error comes up then you don't pass the test.  Also this commit has a bunch of garbage files in it.  You should just be committing the files that are part of the code base.

If you want to try a different test (I just added an about button test while trying to figure out what wa going on here) pull from staging and restart.

**Comment by adrianhumphrey111** [comment]
I am confused as to which staging to check out? When I check out the staging file, I do not get the same files that are on Github.   
  
  
  

  
  
>

**Comment by adrianhumphrey111** [comment]
The last staging I see is December 6, 2016.   
  
    
  
  
  
  
      
  

  
>

**Comment by djp3** [comment]
Are you looking at your staging branch or djp3:staging?

**Comment by djp3** [comment]
Because staging is my default branch on github now:  see: https://github.com/djp3/sbfoodbank

**Comment by adrianhumphrey111** [comment]
I think that may be the problem. How do I pull from djp3:staging through source tree?
    
  

  
  
>

**Comment by djp3** [comment]
Make sure that you have my github repository listed on your remotes.  Then "Fetch" from all remotes so that you can see where every branch is at.  Then right-click and branch from djp3/staging on the history view.

**Comment by adrianhumphrey111** [comment]
I think that may be the problem. How do I pull from djp3:staging through source tree?
    
  

  
  
>

**Pull request closed without merging**
